### ISSUE TITLE
Using the MUI component props

### ISSUE THREAD

**Issue by kingedward35** [ajnsit/purescript-concur-react-mui#1]
I don't know if this is the right place to put this, but I was wondering if you knew how to use the imported MUI component props in Purescript-Concur? For example, if I import `classButton` and want to use a `variant` of `contained`, what syntax would I use in Concur for the button to have the MUI props respect that?  Thanks.

**Comment by kingedward35** [comment]
I think I just figured it out. Looks like if you use this function `unsafeMkProp`, you can mimic the MUI props. If there is a better way than this, I would appreciate your feedback. Thanks again.

**Comment by ajnsit** [comment]
Yup, `unsafeMkProp` is the way to go!
