### ISSUE TITLE
OK to add components outside of material-ui/core?

### ISSUE THREAD

**Issue by bbarker** [ajnsit/purescript-concur-react-mui#2]
Hi - I was thinking of adding some other components, such as those from [material-ui/pickers](https://material-ui.com/components/pickers/#date-time-pickers). Would those be welcome here, or should I create a separate repository?

Thanks!

**Comment by ajnsit** [comment]
Yeah, they are absolutely welcome here! Please feel free to add them. I can add you as a maintainer on this repository if you want, so I'm not a bottleneck.
